In [1]:
import numpy as np

In [56]:
### build player ###
player = [1,2,3,4];
#print(np.zeros((8,8)))

### build square matrix ###
matrix_size = 4;
game_matrix = (np.zeros((matrix_size,matrix_size)))

### define_match_size

match_size = 3;

for i in range(matrix_size):
    for j in range(matrix_size):
        game_matrix[i,j] = player[np.random.randint(len(player))]

print(game_matrix)


for i in range(matrix_size):
    for j in range(matrix_size):
        if (i == 0 and j == 0 ) or (i == 0 and j == matrix_size-1 ) or (i == matrix_size-1 and j == 0 ) or (i == matrix_size-1 and j == matrix_size-1 ):
            #print("corner",i,j)
            pass
        elif (i == 0) or (i == matrix_size-1):
            #print("check horizontal",i,j)
            if (game_matrix[i,j] == game_matrix[i,j-1]) and (game_matrix[i,j] == game_matrix[i,j+1]):
                print("hori_bingo",i,j)
        elif (j == 0) or (j == matrix_size-1):
            #print("check vertical",i,j)
            if (game_matrix[i,j] == game_matrix[i-1,j]) and (game_matrix[i,j] == game_matrix[i+1,j]):
                print("verti_bingo",i,j)
        else:
            #print("check horizontal","check vertical",i,j)
            if (game_matrix[i,j] == game_matrix[i-1,j]) and (game_matrix[i,j] == game_matrix[i+1,j]):
                print("verti_bingo",i,j)
            elif (game_matrix[i,j] == game_matrix[i,j-1]) and (game_matrix[i,j] == game_matrix[i,j+1]):
                print("hori_bingo",i,j)






[[1. 1. 4. 4.]
 [4. 2. 4. 2.]
 [1. 2. 4. 2.]
 [4. 2. 2. 4.]]
verti_bingo 1 2
verti_bingo 2 1
