In [2]:
import numpy as np

In [91]:
### build player ###
player = [1,2,3,4];
#print(np.zeros((8,8)))

### build square matrix ###
matrix_size = 4;
game_matrix = (np.zeros((matrix_size,matrix_size)))

### define_match_size

match_size = 3;

for i in range(matrix_size):
    for j in range(matrix_size):
        game_matrix[i,j] = player[np.random.randint(len(player))]

print(game_matrix)

###judge bingo
#clean_hori_matrix_row = [];
#clean_hori_matrix_col = [];
#clean_verti_matrix_row = [];
#clean_verti_matrix_col = [];

clean_matrix_row = [];
clean_matrix_col = [];
clean_matrix_cat = []; #hori oder verti

hori_bingo_num = 0
verti_bingo_num = 0
for i in range(matrix_size):
    for j in range(matrix_size):
        if (i == 0 and j == 0 ) or (i == 0 and j == matrix_size-1 ) or (i == matrix_size-1 and j == 0 ) or (i == matrix_size-1 and j == matrix_size-1 ):
            #print("corner",i,j)
            pass
        elif (i == 0) or (i == matrix_size-1):
            #print("check horizontal",i,j)
            if (game_matrix[i,j] == game_matrix[i,j-1]) and (game_matrix[i,j] == game_matrix[i,j+1]):
                print("hori_bingo",i,j)
                clean_matrix_row.append(i);
                clean_matrix_col.append(j);
                clean_matrix_cat.append('h');
#                clean_hori_matrix_row.append(i);
#                clean_hori_matrix_col.append(j);
                hori_bingo_num += 1
        elif (j == 0) or (j == matrix_size-1):
            #print("check vertical",i,j)
            if (game_matrix[i,j] == game_matrix[i-1,j]) and (game_matrix[i,j] == game_matrix[i+1,j]):
                print("verti_bingo",i,j)
                clean_matrix_row.append(i);
                clean_matrix_col.append(j);
                clean_matrix_cat.append('v');
#                clean_verti_matrix_row.append(i);
#                clean_verti_matrix_col.append(j);
                verti_bingo_num += 1
        else:
            #print("check horizontal","check vertical",i,j)
            if (game_matrix[i,j] == game_matrix[i-1,j]) and (game_matrix[i,j] == game_matrix[i+1,j]):
                print("verti_bingo",i,j)
                clean_matrix_row.append(i);
                clean_matrix_col.append(j);
                clean_matrix_cat.append('v');
#                clean_verti_matrix_row.append(i);
#                clean_verti_matrix_col.append(j);
                verti_bingo_num += 1
            elif (game_matrix[i,j] == game_matrix[i,j-1]) and (game_matrix[i,j] == game_matrix[i,j+1]):
                print("hori_bingo",i,j)
                clean_matrix_row.append(i);
                clean_matrix_col.append(j);
                clean_matrix_cat.append('h');
#                clean_hori_matrix_row.append(i);
#                clean_hori_matrix_col.append(j);
                hori_bingo_num += 1

#print('hori',clean_hori_matrix_row,clean_hori_matrix_col)
#print('verti',clean_verti_matrix_row,clean_verti_matrix_col)
print(clean_matrix_row,clean_matrix_col);
print(clean_matrix_cat);
print('verti_bingo_num', verti_bingo_num,'hori_bingo_num', hori_bingo_num)


[[2. 4. 1. 1.]
 [3. 2. 1. 1.]
 [1. 1. 1. 4.]
 [2. 4. 3. 4.]]
verti_bingo 1 2
hori_bingo 2 1
[1, 2] [2, 1]
['v', 'h']
verti_bingo_num 1 hori_bingo_num 1


In [92]:
print('first matrix')
print(game_matrix)

game_matrix_1 = game_matrix

###gernerate new elements
bingo_num = len(clean_matrix_row)
new_element_num = bingo_num * 3

#for nen in range(new_element_num):
#    new_element = np.random.randint(new_element_num)
#    print(new_element)
###gernerate new elements

bn_idx = bingo_num-1
for bn in range(bingo_num):
 #   print(clean_matrix_row[bn_idx]);
    if clean_matrix_cat[bn_idx] == 'h':
#        print(clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]+1);
#        print(clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]);
#        print(clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]-1);
        game_matrix_1[clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]+1] = 0;
        game_matrix_1[clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]] = 0;
        game_matrix_1[clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]-1] = 0;
    elif clean_matrix_cat[bn_idx] == 'v':
#        print(clean_matrix_row[bn_idx]+1,clean_matrix_col[bn_idx]);
#        print(clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]);
#        print(clean_matrix_row[bn_idx]-1,clean_matrix_col[bn_idx]);
        game_matrix_1[clean_matrix_row[bn_idx]+1,clean_matrix_col[bn_idx]] = 0;
        game_matrix_1[clean_matrix_row[bn_idx],clean_matrix_col[bn_idx]] = 0;
        game_matrix_1[clean_matrix_row[bn_idx]-1,clean_matrix_col[bn_idx]] = 0;
        pass
    else:
        break
    bn_idx -= 1;

print(game_matrix_1)
#print(sum(game_matrix_1[:,0] == 0) )
#print(sum(game_matrix_1[:,1] == 0) )
#print(sum(game_matrix_1[:,2] == 0) )
#print(sum(game_matrix_1[:,3] == 0) )

#print(game_matrix_1[:,3])

row_idx = matrix_size;
col_idx = matrix_size;
point_idx = 0;

game_matrix_2 = game_matrix_1;

for i in range(matrix_size):
    col_idx -= 1;
    for j in range(matrix_size):
        row_idx -= 1;
        print(row_idx,col_idx)
        while game_matrix_2[row_idx,col_idx] == 0:
            rrow_idx = row_idx;
            ccol_idx = col_idx;
            for k in range(row_idx):
                game_matrix_2[rrow_idx,ccol_idx] = game_matrix_2[rrow_idx-1,ccol_idx]
                rrow_idx -= 1;
            game_matrix_2[rrow_idx,ccol_idx] = player[np.random.randint(len(player))]
    row_idx = matrix_size;   
    point_idx = 0;

#print(game_matrix_2)

first matrix
[[2. 4. 1. 1.]
 [3. 2. 1. 1.]
 [1. 1. 1. 4.]
 [2. 4. 3. 4.]]
[[2. 4. 0. 1.]
 [3. 2. 0. 1.]
 [0. 0. 0. 4.]
 [2. 4. 3. 4.]]
3 3
2 3
1 3
0 3
3 2
2 2
1 2
0 2
3 1
2 1
1 1
0 1
3 0
2 0
1 0
0 0


In [93]:
print(game_matrix_2)

[[1. 3. 2. 1.]
 [2. 4. 3. 1.]
 [3. 2. 2. 4.]
 [2. 4. 3. 4.]]
